//Todo: Create default post
export const CREATE_DEFAULT_POST_SUB = 'CREATE_DEFAULT_POST_SUB';
export const LIKE_DEFAULT_POST_SUB = 'LIKE_DEFAULT_POST_SUB';
export const COMMENT_DEFAULT_POST_SUB = 'COMMENT_DEFAULT_POST_SUB';
export const COMMENT_DEFAULT_POST_COUNT_SUB = 'COMMENT_DEFAULT_POST_COUNT_SUB';